# Generated by Django 2.1.7 on 2019-06-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('subject', models.CharField(max_length=255)),
                ('register_date', models.DateField(auto_now_add=True)),
                ('score', models.DecimalField(decimal_places=1, default=1.0, max_digits=2)),
            ],
        ),
    ]
